// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwGwvHPnGYdQxFDk5KbSReiltmsbIKDzg',
    appId: '1:923027360996:web:087fa87fefa9fb431eb0f1',
    messagingSenderId: '923027360996',
    projectId: 'bhagavad-gita-as-it-is-109d3',
    authDomain: 'bhagavad-gita-as-it-is-109d3.firebaseapp.com',
    storageBucket: 'bhagavad-gita-as-it-is-109d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEbttgxCh9IZkH2tG76iDgcM6z0VwOuk',
    appId: '1:923027360996:android:efafc98eba0e8c231eb0f1',
    messagingSenderId: '923027360996',
    projectId: 'bhagavad-gita-as-it-is-109d3',
    storageBucket: 'bhagavad-gita-as-it-is-109d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECL62CUNIKuKhwVFiHivF9yxUCpw2ZNI',
    appId: '1:923027360996:ios:909157cb3c7641d91eb0f1',
    messagingSenderId: '923027360996',
    projectId: 'bhagavad-gita-as-it-is-109d3',
    storageBucket: 'bhagavad-gita-as-it-is-109d3.firebasestorage.app',
    iosBundleId: 'com.example.gitaAsItIs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECL62CUNIKuKhwVFiHivF9yxUCpw2ZNI',
    appId: '1:923027360996:ios:909157cb3c7641d91eb0f1',
    messagingSenderId: '923027360996',
    projectId: 'bhagavad-gita-as-it-is-109d3',
    storageBucket: 'bhagavad-gita-as-it-is-109d3.firebasestorage.app',
    iosBundleId: 'com.example.gitaAsItIs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwGwvHPnGYdQxFDk5KbSReiltmsbIKDzg',
    appId: '1:923027360996:web:cea38f54c9d5bf701eb0f1',
    messagingSenderId: '923027360996',
    projectId: 'bhagavad-gita-as-it-is-109d3',
    authDomain: 'bhagavad-gita-as-it-is-109d3.firebaseapp.com',
    storageBucket: 'bhagavad-gita-as-it-is-109d3.firebasestorage.app',
  );
}
